#!/usr/bin/env bash

set -e

# Applies patch for preventing WordPress updates
main() {
    local patchFile="${1:?PATCH_FILE is required}"
    local targetFile="${2:?TARGET_FILE is required}"

    if [ ! -f "${patchFile}" ]; then
        echo ">	No such	file [PATCH]: ${patchFile}"
        return 1
    fi

    if [ ! -f "${targetFile}" ]; then
        echo "> No such file [TARGET]: ${targetFile}"
        return 1
    fi

    echo "> Loading patch ${patchFile}"
    echo "  Patching '${targetFile}'..."
    patch --verbose "${targetFile}" <"${patchFile}"

    local markReadOnly="${3:-true}"
    if [ "${markReadOnly}" = "true" ]; then
        # This is done in order to prevent WordPress overwriting the file
        echo "  Marking the patched file read-only..."
        chmod 0440 "${targetFile}"
    fi

    return 0
}

# Usage: main /etc/wp-mods/wp-admin-update-core.patch /var/www/html/wp-admin/update-core.php ?true|false
main "${@}"
exit $?
