#!/usr/bin/env bash

main() {
    local secretsDir="${DOCKER_SECRETS_DIR:-./.secrets}"
    local keys=("AUTH_KEY" "SECURE_AUTH_KEY" "LOGGED_IN_KEY" "NONCE_KEY" "AUTH_SALT" "SECURE_AUTH_SALT" "LOGGED_IN_SALT" "NONCE_SALT")

    mkdir -p "${secretsDir}"

    for key in "${keys[@]}"; do
        value="$(src/utils/random-string 64)"
        secretName="wordpress_${key,,}"
        secretFile="${secretsDir}/${secretName}"

        if [ -f "${secretFile}" ]; then
            printf "Warning: Secret %s already exists and will be overwritten\n" "${secretName}"
        fi

        printf "Secret %s: Wrote %d bytes to %s\n" "${secretName}" "${#value}" "${secretFile}"
        printf "%s" "${value}" > "${secretFile}"
    done
}

main "${@}"
