ARG WP_VERSION=6.5.3
FROM scratch AS rootfs

# Install composer
COPY --from=composer:2.7 ["/usr/bin/composer", "/usr/local/bin/composer"]

# Install shellcheck
COPY --from=koalaman/shellcheck:stable ["/bin/shellcheck", "/usr/local/bin/shellcheck"]

# Install shfmt
COPY --from=mvdan/shfmt:latest ["/bin/shfmt", "/usr/local/bin/shfmt"]



ARG WP_VERSION
FROM ghcr.io/n0rthernl1ghts/wordpress:${WP_VERSION}

RUN set -eux \
    && apk add --update --no-cache exa file fish git less nano openssh-client rsync tree unzip wget

COPY --from=rootfs ["/", "/"]


WORKDIR "/workspace"
ENTRYPOINT ["/usr/bin/fish"]
