#!/usr/bin/with-contenv bash
set -e

PLUGIN_LIST="${WORDPRESS_PLUGIN_LIST:-}"
WP_CONTENT_PATH="/var/www/${WEB_ROOT}/wp-content"

echo "> Automated WordPress Plugin Installer"

if [ -z "${PLUGIN_LIST}" ]; then
  echo "> No plugins defined. Skipping installation."
  exit 0
fi

echo "> About to install defined plugins"
for PLUGIN_EXPR in ${PLUGIN_LIST}; do
  IFS=':' read -ra PLUGIN <<<"${PLUGIN_EXPR}"

  PLUGIN_PATH="${WP_CONTENT_PATH}/plugins/${PLUGIN[0]}"

  if [ -d "${PLUGIN_PATH}" ] || [ -f "${PLUGIN_PATH}.php" ]; then
    echo "> Plugin '${PLUGIN[0]}' already installed and will be skipped."
    continue
  fi

  WP_PLUGIN_INSTALL_ARGS="${PLUGIN[0]}"

  if [ -n "${PLUGIN[1]}" ]; then
    WP_PLUGIN_INSTALL_ARGS="${WP_PLUGIN_INSTALL_ARGS} --version=${PLUGIN[1]}"
  fi

  echo "> Installing plugin '${PLUGIN[0]}' version '${PLUGIN[1]}'"
  wp plugin install ${WP_PLUGIN_INSTALL_ARGS}
done