#!/usr/bin/with-contenv sh
set -e

echo "Redirecting nginx logs to output streams..."

# General logs
ln -sf /dev/stdout /var/log/nginx/access.log
ln -sf /dev/stderr /var/log/nginx/error.log

# App specific logs
ln -sf /dev/stdout /var/log/nginx/app-access.log
ln -sf /dev/stderr /var/log/nginx/app-error.log
