#!/usr/bin/env bash

main() {
    echo "Warning: This is resource-intensive and might crash your system if you don't have enough resources !!!"
    echo "Press Ctrl+C to cancel. Automatically continuing in 5 seconds..."
    sleep 5

    docker buildx bake --file hack/docker-bake.hcl --pull "${@}" &
    docker buildx bake --file hack/docker-bake-cron.hcl --pull "${@}" &
    wait
}

main "${@}"
